backend:
  name: github
  branch: main
  repo: writechoiceorg/test-decap
  commit_messages:
    create: doc:create {{collection}} by {{author-name}} at “{{slug}}”
    update: doc:update {{collection}} by {{author-name}} at “{{slug}}”
    delete: doc:delete {{collection}} by {{author-name}} at “{{slug}}”
    uploadMedia: doc:upload image “{{path}}”
    deleteMedia: doc:delete image “{{path}}”
    openAuthoring: '{{message}}'

publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "my-website/static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: blog
  label: "blog"
  folder: my-website/blog
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }
    - { name: slug, label: Slug, widget: string }
    - label: "Tags"
      name: "tags"
      widget: "list"
    - label: "Authors"
      name: "authors" 
      widget: "list"
      fields:
        - { name: name, label: Name, widget: string }
        - { name: title, label: Title, widget: string } 
- name: docs
  label: Docs
  label_singular: Doc
  folder: docs
  create: true
  nested:
    depth: 4 
    summary: '{{title}}' 
  fields:
    - label: Sidebar position
      name: sidebar_position
      widget: number
    - label: Title
      name: title
      widget: string
    - label: Description
      name: description
    - label: Image
      name: image
      widget: 'image'
      allow_multiple: false
    - label: Body
      name: body
      widget: markdown
  sortableFields: ["title", "sidebar_position"]
  extension: md
  format: frontmatter
  editor:
    preview: false
  meta: { path: { widget: string, label: 'Path', index_file: 'index' } }          